[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = '0.8.17'
gas_reports = ["*"]

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_KEY}" }

[fuzz]
runs = 50000

[invariant]
runs = 256
depth = 256